# Stateful service descriptor for the gateway app
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: frontend
spec:
  containers:
  - image: justinhj/frontend:latest
    name: frontend
