# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: my-service
spec:
  # Datastore configuration
  storeConfig:
    database: my-database
    statefulStore:
      # Name of a deployed Datastore to use.
      name: my-postgres
  containers:
    - image: coreyauger/my-service:latest
      name: my-service
