# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: raidboss-service
spec:
  # Datastore configuration
  storeConfig:
    database: raidboss-database
    statefulStore:
      # Name of a deployed Datastore to use.
      name: raidboss-postgres
  containers:
    - image: justinhj/raidboss-service:latest
      name: raidboss-service
      env:
        - name: DEBUG
          value: cloudstate*
