# Route for friends app
apiVersion: cloudstate.io/v1alpha1
kind: Route
metadata:
  name: raidboss-routes
spec:
  http:
  - name: raidboss-routes
    match:
    - uri:
        prefix: /
    route:
      service: raidboss-service
